apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: st
  labels:
    app: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: server
    port: {{ .Values.image.ports.server }}
    targetPort: {{ .Values.image.ports.server }}
    protocol: UDP